blank_issues_enabled: true
contact_links:
  - name: traaittXT Enterprise Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: traaittXT Enterprise Developers
    url: https://bitcoincore.org
    about: traaittXT Enterprise homepage
